language: rust
rust:
  - beta
matrix:
  include:
    - os: osx
      osx_image: xcode12.2
      env: TARGET=x86_64-apple-darwin ARM=aarch64-apple-darwin
    - os: linux
      dist: xenial
      env: TARGET=x86_64-unknown-linux-gnu WIN=x86_64-pc-windows-gnu
      sudo: required
      addons:
        apt:
          packages:
            - gcc-mingw-w64

if: tag IS present
install: cargo install --force --path .
script: true
cache: cargo
before_deploy:
  - cargo build --release --target=$TARGET && mv target/release/badlogvis target/release/badlogvis-$TARGET
  - .ci/cross-build.sh
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: target/**/release/badlogvis-{$TARGET,$ARM,$WIN.exe}
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
