name: Build Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-11.0
            TARGET: x86_64-apple-darwin
            SECONDARY: aarch64-apple-darwin
          - os: ubuntu-latest
            TARGET: x86_64-unknown-linux-gnu
            SECONDARY: x86_64-pc-windows-gnu
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          target: ${{ matrix.SECONDARY }} # This is in addition to the native target
          profile: minimal
      - name: Build for ${{ matrix.TARGET }}
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Install Windows linker
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install gcc-mingw-w64 &&
          printf "[x86_64-pc-windows-gnu]\nlinker = \"x86_64-w64-mingw32-gcc\"" >> ~/.cargo/config
      - name: Build for ${{ matrix.SECONDARY }}
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.SECONDARY }}
      - name: Package binaries
        id: package_binaries
        env:
          TARGET: ${{ matrix.TARGET }}
          SECONDARY: ${{ matrix.SECONDARY }}
        run: .ci/package.sh
      - name: Publish release with binaries
        id: publish_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          name: badlogvis ${{ env.RELEASE_VERSION }}
          draft: false
          prerelease: false
          files: |
            ./out/badlogvis-*.tar.gz
            ./out/badlogvis-*.zip


